transformer_additional_kwargs:
  patch_3d:                                   false
  fake_3d:                                    false
  basic_block_type:                           "motionmodule"
  time_position_encoding_before_transformer:  false
  motion_module_type:                         "Vanilla"
  enable_uvit:                                true
  
  motion_module_kwargs:
    num_attention_heads:                8
    num_transformer_block:              1
    attention_block_types:              [ "Temporal_Self", "Temporal_Self" ]
    temporal_position_encoding:         true
    temporal_position_encoding_max_len: 4096
    temporal_attention_dim_div:         1
    block_size:                         1

noise_scheduler_kwargs:
  num_train_timesteps:    1000
  shift: 1.0

vae_kwargs:
  enable_magvit: true
  slice_compression_vae: true
  mini_batch_encoder: 8
